import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "پنل حقوق و دستمزد صدرا",
  description: "Generated by amisa.me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body>{children}</body>
    </html>
  );
}
